name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    env:
      SOURCE_DIR: 'source'
      BUILD_DIR: 'build'
      FORMAT_HTML: 'html'
      FORMAT_PDF: 'latexpdf'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Cache apt packages
        id: cache-apt-packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-texlive        
        
      - name: Install LaTeX
        run: |
          sudo apt install -y \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            tex-gyre \
            texlive-latex-extra \
            latexmk \
            fonts-font-awesome
      - name: Install latest Sphinx and myST Parser
        run: |
          # Install Sphinx and myst-parser
          pip install -r requirements.txt
      - name: Build HTML
        run: |
          # Assuming BUILDDIR is "build", and format is "html",
          # Output will be in ./<build>/<format>/ directory
          sphinx-build -M $FORMAT_HTML $SOURCE_DIR $BUILD_DIR
      - name: Build PDF
        run: |
          sphinx-build -M $FORMAT_PDF $SOURCE_DIR $BUILD_DIR LATEXOPTS="--halt-on-error"
      - name: Find PDF
        run: |
          find . -name trysphinx.pdf
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "${{ env.BUILD_DIR }}/${{ env.FORMAT_HTML }}"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        